server:
  port: 8004
spring:
  data:
    mongodb:
      uri: mongodb://34.100.165.148:27017/emaildb
email:
  host: smtp.gmail.com
  port: 587
  username: parthiban.geetham@gmail.com
  password: dxinucxmqvsoybuf
